workflows:
  android-workflow:
    name: PrisonPay Build
    max_build_duration: 30
    environment:
      java: 17
    scripts:
      - echo "🔓 Ensure gradlew.sh is executable"
      - chmod +x gradlew.sh
      - echo "📂 Listing files in root for debugging"
      - ls -R .
      - echo "🧹 Cleaning the project"
      - ./gradlew.sh clean
      - echo "🏗️ Building APK..."
      - ./gradlew.sh assembleDebug
    artifacts:
      - app/build/outputs/**/*.apk
    publishing:
      email:
        recipients:
          - mrarnoldsd@gmail.com
