workflows:
  android-workflow:
    name: PrisonPay Build
    max_build_duration: 30
    environment:
      java: 17
      android: sdk
    scripts:
      - echo "📂 Debugging file structure:"
      - ls -R .
      - echo "🧹 Cleaning the project..."
      - gradle clean
      - echo "🏗️ Building APK..."
      - gradle assembleDebug
    artifacts:
      - app/build/outputs/**/*.apk
    publishing:
      email:
        recipients:
          - mrarnoldsd@gmail.com
