workflows:
  android-workflow:
    name: Build PrisonPay Debug APK
    max_build_duration: 30
    environment:
      vars:
        PACKAGE_NAME: "com.prisonpay.app"
      java: 17
      android_signing: null
    scripts:
      - name: Clean project
        script: ./gradlew clean
      - name: Assemble Debug APK
        script: ./gradlew assembleDebug
    artifacts:
      - app/build/outputs/**/*.apk
    publishing:
      email:
        recipients:
          - your-email@example.com