workflows:
  android-workflow:
    name: PrisonPay Build
    max_build_duration: 30
    environment:
      vars:
        PACKAGE_NAME: "com.prisonpay.app"
      java: 17
    scripts:
      - echo "🔓 Setting gradlew.sh permission"
      - chmod +x gradlew.sh
      - echo "🧹 Cleaning project..."
      - ./gradlew.sh clean
      - echo "🏗️ Building APK..."
      - ./gradlew.sh assembleDebug
    artifacts:
      - app/build/outputs/**/*.apk
    publishing:
      email:
        recipients:
          - mrarnoldsd@gmail.com
        notify:
          success: true
          failure: true
